import { StyleSheet } from 'react-native';

import { colors, radii, shadows } from '@/constants/theme';

export const profileScreenStyles = StyleSheet.create({
  avatar: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderRadius: 999,
    height: 72,
    justifyContent: 'center',
    width: 72,
  },
  avatarInitials: {
    color: colors.foreground,
    fontSize: 24,
    fontWeight: '800',
  },
  avatarWrap: {
    position: 'relative',
  },
  bloodTypePill: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.primarySoft,
    borderRadius: radii.pill,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  bloodTypePillText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '700',
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: radii.card,
    gap: 16,
    padding: 20,
    ...shadows.card,
  },
  cardTitle: {
    color: colors.foreground,
    fontSize: 16,
    fontWeight: '800',
  },
  contactIconWrap: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderRadius: 999,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  contactLabel: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '600',
  },
  contactRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
  },
  contactValue: {
    color: colors.foreground,
    fontSize: 15,
    fontWeight: '600',
  },
  contactValueWrap: {
    flex: 1,
    gap: 2,
  },
  divider: {
    backgroundColor: colors.border,
    height: 1,
    width: '100%',
  },
  donationBadgeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  donationBloodBadge: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderRadius: radii.pill,
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  donationBloodBadgeText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
  },
  donationDate: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '500',
  },
  donationDateRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  donationHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  donationHospital: {
    color: colors.foreground,
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
  },
  donationIconWrap: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderRadius: 999,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  donationItem: {
    backgroundColor: '#f8fafc',
    borderRadius: 14,
    gap: 10,
    padding: 14,
  },
  donationMetaRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'space-between',
  },
  donationStatusPill: {
    alignItems: 'center',
    backgroundColor: colors.successSoft,
    borderRadius: radii.pill,
    flexDirection: 'row',
    flexShrink: 0,
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  donationStatusPillActive: {
    backgroundColor: colors.infoSoft,
  },
  donationStatusText: {
    color: colors.success,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'capitalize',
  },
  donationStatusTextActive: {
    color: colors.infoText,
  },
  donationTextWrap: {
    flex: 1,
    gap: 2,
  },
  donationUnitsText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  actionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    width: '100%',
  },
  editProfileButton: {
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: 12,
    paddingVertical: 10,
    width: '100%',
  },
  editProfileButtonDonor: {
    flex: 1.1,
    minWidth: 0,
    paddingHorizontal: 8,
    width: 'auto',
  },
  editProfileText: {
    color: colors.foreground,
    fontSize: 13,
    fontWeight: '700',
  },
  qrButton: {
    alignItems: 'center',
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  availabilityCard: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderRadius: 12,
    flex: 1.3,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 46,
    minWidth: 0,
    paddingHorizontal: 10,
  },
  availabilityCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  availabilityTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  availabilityTitle: {
    color: colors.foreground,
    fontSize: 12,
    fontWeight: '700',
  },
  availabilityStatus: {
    color: colors.mutedLight,
    fontSize: 11,
    fontWeight: '600',
  },
  availabilityStatusActive: {
    color: colors.success,
    fontWeight: '700',
  },
  availabilityError: {
    color: colors.primary,
    fontSize: 13,
    lineHeight: 18,
    marginTop: -8,
  },
  availabilityHint: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
    marginTop: -8,
  },
  emptyDonationsText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  header: {
    backgroundColor: colors.card,
    paddingBottom: 16,
    paddingHorizontal: 24,
  },
  headerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  headerSettingsButton: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderRadius: 999,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  headerTitle: {
    color: colors.foreground,
    fontSize: 22,
    fontWeight: '800',
  },
  linkText: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: '700',
  },
  logoutButton: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: radii.card,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    paddingVertical: 16,
    ...shadows.card,
  },
  logoutText: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '700',
  },
  menuBadge: {
    alignItems: 'center',
    backgroundColor: colors.info,
    borderRadius: 999,
    height: 22,
    justifyContent: 'center',
    minWidth: 22,
    paddingHorizontal: 6,
  },
  menuBadgeText: {
    color: colors.primaryForeground,
    fontSize: 11,
    fontWeight: '800',
  },
  menuIconWrap: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderRadius: 999,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  menuLabel: {
    color: colors.foreground,
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
  },
  menuRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 14,
  },
  menuRowDivider: {
    backgroundColor: colors.border,
    height: 1,
  },
  profileCard: {
    backgroundColor: colors.card,
    borderRadius: radii.card,
    gap: 20,
    padding: 20,
    ...shadows.card,
  },

  statDivider: {
    backgroundColor: colors.border,
    height: '60%',
    width: 1,
    alignSelf: 'center',
  },
  overviewHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 16,
  },
  nameRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    minWidth: 0,
  },
  overviewMeta: {
    flex: 1,
    gap: 6,
  },

  roleLabel: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: '500',
  },
  screen: {
    backgroundColor: colors.background,
    flex: 1,
  },
  scrollContent: {
    gap: 20,
    paddingBottom: 32,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statColumn: {
    alignItems: 'center',
    flex: 1,
    gap: 4,
  },
  statLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  statRow: {
    flexDirection: 'row',
    gap: 8,
  },
  statValue: {
    color: colors.foreground,
    fontSize: 22,
    fontWeight: '800',
  },
  statValuePrimary: {
    color: colors.primary,
    fontSize: 22,
    fontWeight: '800',
  },
  statValueSuccess: {
    color: colors.success,
    fontSize: 22,
    fontWeight: '800',
  },
  statValueWarning: {
    color: colors.warning,
    fontSize: 22,
    fontWeight: '800',
  },
  userName: {
    color: colors.foreground,
    flexShrink: 1,
    fontSize: 20,
    fontWeight: '800',
  },
  verifiedBadge: {
    alignSelf: 'flex-start',
    backgroundColor: colors.successSoft,
    borderRadius: radii.pill,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  verifiedBadgeOnAvatar: {
    alignItems: 'center',
    backgroundColor: colors.success,
    borderColor: colors.card,
    borderRadius: 999,
    borderWidth: 2,
    bottom: 0,
    height: 22,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    width: 22,
  },
  verifiedBadgeText: {
    color: colors.success,
    fontSize: 12,
    fontWeight: '700',
  },
});
