import { StyleSheet } from 'react-native';

import { colors, radii, shadows } from '@/constants/theme';

export const donorHomeStyles = StyleSheet.create({
  availabilityCard: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: radii.card,
    flexDirection: 'row',
    gap: 12,
    padding: 16,
    ...shadows.card,
  },
  availabilityCopy: {
    flex: 1,
    gap: 2,
  },
  availabilityIcon: {
    alignItems: 'center',
    backgroundColor: colors.background,
    borderRadius: 999,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  availabilityError: {
    color: colors.primary,
    fontSize: 13,
    lineHeight: 18,
  },
  availabilityHint: {
    color: colors.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  availabilityStatus: {
    color: colors.mutedLight,
    fontSize: 14,
    fontWeight: '600',
  },
  availabilityTitle: {
    color: colors.foreground,
    fontSize: 15,
    fontWeight: '700',
  },
  bloodTypeCard: {
    backgroundColor: colors.card,
    borderRadius: radii.card,
    gap: 12,
    padding: 16,
    ...shadows.card,
  },
  bloodTypeFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
  },
  bloodTypeLabel: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '600',
  },
  bloodTypeMeta: {
    color: colors.mutedLight,
    flex: 1,
    fontSize: 14,
  },
  bloodTypeRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
  },
  greeting: {
    color: colors.foreground,
    fontSize: 22,
    fontWeight: '800',
  },
  header: {
    backgroundColor: colors.background,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    paddingBottom: 16,
    paddingHorizontal: 24,
    paddingTop: 0,
  },
  headerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modeToggleRow: {
    marginTop: 12,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: 999,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  linkText: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: '700',
  },
  loadErrorCard: {
    backgroundColor: colors.card,
    borderRadius: radii.card,
    gap: 12,
    padding: 16,
  },
  notificationDot: {
    backgroundColor: colors.info,
    borderColor: colors.card,
    borderRadius: 999,
    borderWidth: 2,
    height: 10,
    position: 'absolute',
    right: 8,
    top: 8,
    width: 10,
  },
  roleLabel: {
    color: colors.muted,
    fontSize: 14,
  },
  screen: {
    backgroundColor: colors.background,
    flex: 1,
  },
  scrollContent: {
    gap: 16,
    padding: 24,
    paddingBottom: 110,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: colors.foreground,
    fontSize: 18,
    fontWeight: '800',
  },
  avatarBox: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 999,
    borderWidth: 1,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  avatarText: {
    color: colors.foreground,
    fontSize: 14,
    fontWeight: '700',
  },
  headerUserRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  userNameText: {
    color: colors.foreground,
    fontSize: 17,
    fontWeight: '800',
  },
  userBloodBadge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.primarySoft,
    borderRadius: 6,
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  userBloodBadgeText: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '700',
  },
  quickFeatureGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  quickFeatureCol: {
    alignItems: 'center',
    flex: 1,
    gap: 6,
  },
  quickFeatureBtn: {
    alignItems: 'center',
    borderRadius: 16,
    height: 60,
    justifyContent: 'center',
    width: '100%',
    ...shadows.card,
  },
  quickFeatureBadge: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 999,
    height: 18,
    justifyContent: 'center',
    paddingHorizontal: 4,
    position: 'absolute',
    right: 4,
    top: 4,
    minWidth: 18,
  },
  quickFeatureBadgeText: {
    color: colors.primaryForeground,
    fontSize: 10,
    fontWeight: '800',
  },
  quickFeatureLabel: {
    color: colors.foreground,
    fontSize: 12,
    fontWeight: '600',
  },
  sectionTitleRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  countBadge: {
    backgroundColor: colors.primarySoft,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  countBadgeText: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '700',
  },
  statRow: {
    flexDirection: 'row',
    gap: 12,
  },
  urgentList: {
    gap: 12,
  },
  viewAllButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 2,
    paddingVertical: 4,
  },
  quickBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    marginVertical: 2,
  },
  quickItem: {
    alignItems: 'center',
    flex: 1,
    gap: 6,
  },
  quickIconButton: {
    alignItems: 'center',
    borderRadius: 14,
    height: 52,
    justifyContent: 'center',
    width: 52,
    borderWidth: 1,
    borderColor: colors.border,
  },
  quickBadge: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 999,
    height: 18,
    justifyContent: 'center',
    position: 'absolute',
    right: -4,
    top: -4,
    width: 18,
    borderWidth: 1.5,
    borderColor: colors.card,
  },
  quickBadgeText: {
    color: colors.primaryForeground,
    fontSize: 10,
    fontWeight: '800',
  },
  quickLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
  },
});
