import { StyleSheet } from 'react-native';

import { colors, radii, shadows } from '@/constants/theme';

export const nearbyDonorsMapStyles = StyleSheet.create({
  bottomOverlay: {
    bottom: 16,
    gap: 10,
    left: 16,
    position: 'absolute',
    right: 16,
    zIndex: 6,
  },
  chip: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    minHeight: 38,
    paddingHorizontal: 14,
    ...shadows.card,
  },
  chipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.border,
  },
  chipLabel: {
    color: colors.foreground,
    fontSize: 13,
    fontWeight: '600',
  },
  chipLabelActive: {
    color: colors.primaryForeground,
    fontWeight: '700',
  },
  chipRow: {
    gap: 8,
    paddingHorizontal: 16,
    paddingRight: 24,
  },
  chipScroll: {
    flexGrow: 0,
  },
  detailActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  detailCard: {
    backgroundColor: colors.card,
    borderRadius: radii.cardLg,
    gap: 10,
    padding: 18,
    ...shadows.card,
  },
  detailClose: {
    alignItems: 'center',
    height: 32,
    justifyContent: 'center',
    position: 'absolute',
    right: 12,
    top: 12,
    width: 32,
    zIndex: 2,
  },
  detailEyebrow: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  detailMeta: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
    paddingRight: 28,
  },
  detailPrimaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 14,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  detailPrimaryLabel: {
    color: colors.primaryForeground,
    fontSize: 15,
    fontWeight: '700',
  },
  detailSecondaryButton: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  detailSecondaryLabel: {
    color: colors.muted,
    fontSize: 15,
    fontWeight: '700',
  },
  detailTitle: {
    color: colors.foreground,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 24,
    paddingRight: 28,
  },
  donorList: {
    gap: 12,
    paddingBottom: 12,
  },
  donorSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  donorSectionTitle: {
    color: colors.foreground,
    fontSize: 18,
    fontWeight: '800',
  },
  emptyCard: {
    backgroundColor: colors.card,
    borderRadius: radii.card,
    gap: 12,
    padding: 20,
    ...shadows.card,
  },
  emptyOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: 'center',
    backgroundColor: 'rgba(249, 250, 251, 0.92)',
    justifyContent: 'center',
    paddingHorizontal: 28,
    zIndex: 5,
  },
  emptyText: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
  },
  errorText: {
    color: colors.primary,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 8,
  },
  filterButton: {
    alignItems: 'center',
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  filterLink: {
    color: colors.muted,
    fontSize: 15,
    fontWeight: '700',
  },
  listModalBody: {
    backgroundColor: colors.card,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    gap: 16,
    maxHeight: '78%',
    paddingBottom: 28,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  listModalHandle: {
    alignSelf: 'center',
    backgroundColor: colors.border,
    borderRadius: radii.pill,
    height: 4,
    marginBottom: 8,
    width: 40,
  },
  listModalScrim: {
    backgroundColor: 'rgba(0,0,0,0.35)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  mapControls: {
    gap: 8,
    position: 'absolute',
    right: 16,
    zIndex: 4,
  },
  zoomControls: {
    gap: 8,
    left: 16,
    position: 'absolute',
    zIndex: 4,
  },
  mapControlButton: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 14,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
    ...shadows.card,
  },
  mapControlButtonPressed: {
    opacity: 0.9,
  },
  mapFill: {
    ...StyleSheet.absoluteFill,
  },
  mapLoadingBadge: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.pill,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    marginLeft: 16,
    marginTop: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    ...shadows.card,
  },
  mapLoadingText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '600',
  },
  permissionBanner: {
    backgroundColor: colors.card,
    borderColor: colors.borderAccent,
    borderRadius: radii.card,
    borderWidth: 1,
    gap: 8,
    padding: 14,
    ...shadows.card,
  },
  permissionText: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  screen: {
    backgroundColor: colors.background,
    flex: 1,
  },
  searchInput: {
    color: colors.foreground,
    flex: 1,
    fontSize: 15,
    paddingVertical: 0,
  },
  searchShell: {
    alignItems: 'center',
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radii.cardLg,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginHorizontal: 16,
    minHeight: 50,
    paddingHorizontal: 14,
    ...shadows.card,
  },
  summaryCard: {
    backgroundColor: colors.card,
    borderRadius: radii.cardLg,
    gap: 12,
    padding: 16,
    ...shadows.card,
  },
  summaryMeta: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 18,
  },
  summaryRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  summaryStat: {
    color: colors.success,
    fontSize: 13,
    fontWeight: '700',
  },
  summaryStatMuted: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '600',
  },
  summaryTextBlock: {
    flex: 1,
    gap: 2,
  },
  summaryTitle: {
    color: colors.foreground,
    fontSize: 16,
    fontWeight: '800',
  },
  topOverlay: {
    gap: 10,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 6,
  },
  visibilityCopy: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  visibilityRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  visibilityTitle: {
    color: colors.foreground,
    fontSize: 14,
    fontWeight: '700',
  },
});
