import { StyleSheet } from 'react-native';

import { colors, radii, shadows } from '@/constants/theme';

export const createBloodRequestStyles = StyleSheet.create({
  bloodTypeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  bloodTypeOption: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.border, borderRadius: 11, borderWidth: 1, height: 42, justifyContent: 'center', width: '22.8%' },
  bloodTypeOptionSelected: { backgroundColor: colors.primarySoft, borderColor: colors.primary },
  bloodTypeText: { color: colors.foreground, fontSize: 14, fontWeight: '800' },
  bloodTypeTextSelected: { color: colors.primary },
  confirmButton: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: 14, flex: 1.35, justifyContent: 'center', minHeight: 50, paddingHorizontal: 12 },
  confirmButtonText: { color: colors.primaryForeground, fontSize: 14, fontWeight: '800' },
  cooldownText: { color: colors.warningText, fontSize: 13, lineHeight: 18, textAlign: 'center' },
  divider: { backgroundColor: colors.border, height: 1 },
  editButton: { alignItems: 'center', borderColor: colors.border, borderRadius: 14, borderWidth: 1, flex: 0.9, justifyContent: 'center', minHeight: 50, paddingHorizontal: 12 },
  editButtonText: { color: colors.foreground, fontSize: 14, fontWeight: '700' },
  errorText: { color: colors.primary, fontSize: 13, lineHeight: 18 },
  field: { gap: 8 },
  fieldLabel: { color: colors.foreground, fontSize: 14, fontWeight: '700' },
  footer: { backgroundColor: colors.card, borderTopColor: colors.border, borderTopWidth: 1, gap: 10, paddingHorizontal: 20, paddingTop: 14 },
  header: { alignItems: 'center', backgroundColor: colors.card, borderBottomColor: colors.border, borderBottomWidth: 1, flexDirection: 'row', gap: 12, paddingBottom: 14, paddingHorizontal: 20 },
  headerTitle: { color: colors.foreground, flex: 1, fontSize: 18, fontWeight: '800' },
  helperText: { color: colors.muted, fontSize: 12, lineHeight: 17 },
  input: { color: colors.foreground, flex: 1, fontSize: 15, minHeight: 48, paddingVertical: 12 },
  inputMultiline: { minHeight: 86, textAlignVertical: 'top' },
  inputShell: { backgroundColor: colors.background, borderColor: colors.border, borderRadius: 13, borderWidth: 1, flexDirection: 'row', paddingHorizontal: 14 },
  inputShellError: { borderColor: colors.primary },
  inputShellWithIcon: { alignItems: 'flex-start', gap: 8, paddingTop: 12 },
  intro: { gap: 5, paddingBottom: 2, paddingHorizontal: 2 },
  introSubtitle: { color: colors.muted, fontSize: 14, lineHeight: 20 },
  introTitle: { color: colors.foreground, fontSize: 21, fontWeight: '800', letterSpacing: -0.35 },
  locationButton: { alignItems: 'center', alignSelf: 'flex-start', flexDirection: 'row', gap: 8, minHeight: 38, paddingRight: 10 },
  locationButtonText: { color: colors.foreground, fontSize: 14, fontWeight: '700' },
  locationIcon: { marginTop: 2 },
  manualBadge: { alignSelf: 'flex-start', backgroundColor: colors.background, borderRadius: radii.pill, paddingHorizontal: 10, paddingVertical: 5 },
  manualBadgeText: { color: colors.muted, fontSize: 11, fontWeight: '700', letterSpacing: 0.2, textTransform: 'uppercase' },
  manualFields: { borderLeftColor: colors.primarySoft, borderLeftWidth: 3, gap: 14, paddingLeft: 13 },
  optionalAction: { alignItems: 'center', flexDirection: 'row', gap: 10, minHeight: 42 },
  optionalActionText: { color: colors.foreground, fontSize: 15, fontWeight: '700' },
  optionalField: { gap: 10 },
  optionalFieldHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
  pressed: { opacity: 0.72 },
  privacyNote: { color: colors.muted, fontSize: 12, lineHeight: 17 },
  reviewActions: { flexDirection: 'row', gap: 10 },
  reviewBloodLine: { color: colors.foreground, fontSize: 18, fontWeight: '800' },
  reviewDivider: { backgroundColor: colors.border, height: 1 },
  reviewHeader: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  reviewHeaderCopy: { flex: 1, gap: 4 },
  reviewIcon: { alignItems: 'center', backgroundColor: colors.primarySoft, borderRadius: 14, height: 46, justifyContent: 'center', width: 46 },
  reviewLabel: { color: colors.muted, fontSize: 12, fontWeight: '700', textTransform: 'uppercase', width: 78 },
  reviewRow: { alignItems: 'flex-start', flexDirection: 'row', gap: 10 },
  reviewSheet: { gap: 18, paddingBottom: 24, paddingHorizontal: 20 },
  reviewSubtitle: { color: colors.muted, fontSize: 13, lineHeight: 18 },
  reviewSummary: { backgroundColor: colors.background, borderColor: colors.border, borderRadius: 16, borderWidth: 1, gap: 13, padding: 16 },
  reviewTitle: { color: colors.foreground, fontSize: 19, fontWeight: '800' },
  reviewValue: { color: colors.foreground, flex: 1, fontSize: 14, fontWeight: '600', lineHeight: 19 },
  screen: { backgroundColor: colors.background, flex: 1 },
  scrollContent: { gap: 14, padding: 18, paddingBottom: 28 },
  sectionCard: { backgroundColor: colors.card, borderColor: colors.border, borderRadius: 18, borderWidth: 1, gap: 16, padding: 16, ...shadows.card },
  sectionDescription: { color: colors.muted, fontSize: 12, lineHeight: 17 },
  sectionEyebrow: { color: colors.foreground, fontSize: 12, fontWeight: '800', letterSpacing: 0.65 },
  sectionHeader: { flex: 1, gap: 3 },
  sectionHeaderRow: { alignItems: 'flex-start', flexDirection: 'row', gap: 12 },
  stepperButton: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.border, borderRadius: 10, borderWidth: 1, height: 38, justifyContent: 'center', width: 38 },
  stepperButtonDisabled: { opacity: 0.4 },
  stepperButtonText: { color: colors.foreground, fontSize: 22, fontWeight: '600', lineHeight: 26 },
  stepperShell: { alignItems: 'center', alignSelf: 'flex-start', backgroundColor: colors.background, borderRadius: 12, flexDirection: 'row', gap: 5, padding: 4 },
  stepperUnit: { color: colors.muted, fontSize: 13, fontWeight: '600' },
  stepperValue: { color: colors.foreground, fontSize: 15, fontVariant: ['tabular-nums'], fontWeight: '800', minWidth: 80, textAlign: 'center' },
  submitButton: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: 14, justifyContent: 'center', minHeight: 52 },
  submitButtonDisabled: { opacity: 0.62 },
  submitButtonPressed: { opacity: 0.88 },
  submitButtonText: { color: colors.primaryForeground, fontSize: 16, fontWeight: '800' },
  uploadBox: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.border, borderRadius: 12, borderStyle: 'dashed', borderWidth: 1.5, gap: 8, justifyContent: 'center', minHeight: 100, padding: 16 },
  uploadBoxPressed: { opacity: 0.92 },
  uploadHint: { color: colors.muted, fontSize: 14, fontWeight: '600', textAlign: 'center' },
  uploadName: { color: colors.foreground, fontSize: 13, fontWeight: '600', textAlign: 'center' },
  urgencyGrid: { backgroundColor: colors.background, borderRadius: 12, flexDirection: 'row', gap: 3, padding: 3 },
  urgencyOption: { alignItems: 'center', borderColor: 'transparent', borderRadius: 9, borderWidth: 1, flex: 1, justifyContent: 'center', minHeight: 38, paddingHorizontal: 2 },
  urgencyOptionCriticalSelected: { backgroundColor: colors.criticalSoft, borderColor: colors.criticalSoft },
  urgencyOptionHighSelected: { backgroundColor: colors.orangeSoft, borderColor: colors.orangeSoft },
  urgencyOptionLowSelected: { backgroundColor: colors.card, borderColor: colors.border },
  urgencyOptionMediumSelected: { backgroundColor: colors.warningSoft, borderColor: colors.warningSoft },
  urgencyText: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  urgencyTextCriticalSelected: { color: colors.critical },
  urgencyTextHighSelected: { color: colors.orangeText },
  urgencyTextLowSelected: { color: colors.foreground },
  urgencyTextMediumSelected: { color: colors.warningText },
});
